menu:
# - {name: 'people', url: '/people'}
# - {name: 'publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'Curriculum Vitae', url: '/CV'}
- {name: 'Archives', url: '/archives'}
- {name: 'Contact', url: '/contact'}

archives:
- {name: 'Researches & Thesis', url: 'researches-and-thesis'}
- {name: 'Lecture Notes', url: 'lecture-notes'}
- {name: 'Study Notes & Problems', url: 'study-notes-and-problems'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'google', link: 'mailto:codngus19248@gmail.com'}
- {icon: 'instagram', link: 'https://instagram.com/uhyeon.c'}
- {icon: 'github', link: 'https://github.com/WoohyeonChae'}

contacts:
- {name: 'Woohyeon Chae', title: 'Student', department: 'Theoretical Physics & Programming', institution: 'Gyeonggi Science High School for the Gifted', institution_address: 'Seoul, Republic of Korea', phone: '(+82) 10 6438 7810', email: 'codngus19248@gmail.com', office: 'Gyeonggi Science High School for the Gifted', image: 'assets/img/contact.jpg'}